import express from 'express';
import cors from 'cors';
import multer from 'multer';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { PrismaClient, UserRole } from '@prisma/client';
import { evaluate, options, ScoreInput, ScoreKey } from '../src/rules.js';
import { ocrConfigured, recognizeImage } from './ocr.js';
import dotenv from 'dotenv';
dotenv.config({ path: path.resolve('ocr_server/.env') });

const prisma = new PrismaClient();
const app = express();
const upload = multer({ dest: path.resolve('uploads') });
app.use(cors()); app.use(express.json({limit:'4mb'})); app.use('/uploads', express.static(path.resolve('uploads')));
const keys = Object.keys(options) as ScoreKey[];
const roleFromRequest = (req: express.Request): UserRole => {
  const role = String(req.header('x-role') || 'EVALUATOR').toUpperCase();
  return role === 'APPROVER' ? UserRole.APPROVER : role === 'APPLICANT' ? UserRole.APPLICANT : UserRole.EVALUATOR;
};
const requireRole = (...allowed: UserRole[]) => (req: express.Request, res: express.Response, next: express.NextFunction) => allowed.includes(roleFromRequest(req)) ? next() : res.status(403).json({error:'当前角色无权执行该操作'});
const toScoreInput = (scores:any[]):ScoreInput => Object.fromEntries(keys.map(key=>{const s=scores.find(x=>x.key===key); return [key,{option:s?.option,score:s?.score??undefined,confirmed:s?.confirmed??false,evidence:s?.evidence}]})) as ScoreInput;
const fieldsFromDemo = {region:'江苏一区',district:'江苏',applicant:'王舒怡',hospital:'江苏省肿瘤医院',kol:'张治主任',projectName:'江苏省肿瘤医院肺癌相关学术会议',meetingDate:'2026-09-20',requestedAmount:'3',background:'医院近半年各科室合计送检约50万元，当前月均10万元以上，院内送检占比约60%，已覆盖胸外科及相关科室。',currentSales:'10万元以上',targetSales:'月均新增10万元',benefits:'独立展台、物料展示及会议PPT产品与应用推荐'};
function narrative(a:any,e:any){ const missing=e.missing.length?`待补充：${e.missing.map((k:string)=>({expertLevel:'专家层级',salesTrend:'销量趋势'} as any)[k]||k).join('、')}`:'资料完整'; return `关于${a.region||'待确认'}-${a.applicant||'待确认'}申请的${a.hospital||'待确认'}${a.projectName||'会议项目'}赞助，申请市场部支持${a.requestedAmount??'未填写'}万元，参会权益：${a.benefits||'待确认'}。\n\n【合作背景】${a.background||'申请材料暂未提供合作背景，请补充合作年限、当前销量、院内送检及竞品情况。'}\n\n【会议目标】当前销量${a.currentSales||'待确认'}，目标${a.targetSales||'待确认'}；增长点及新增客户、检测量或科室目标请结合申请材料补充。\n\n【资源覆盖】区域年度投入、医院年度累计支持及历史会议支持情况：待从投入台账核对。\n\n【综合评估】当前已确认评分${e.rawScore}分（百分制${e.percentile}分），对应${e.grade}项目，${missing}。建议支持额度${e.recommendedRange}，默认建议金额${e.defaultAmount}万元；请结合预算、历史投入产出和会议权益确认最终金额。`; }
async function audit(applicationId:string, action:string, after:any, reason?:string){ await prisma.auditLog.create({data:{applicationId,actor:'当前用户',role:UserRole.EVALUATOR,action,afterJson:JSON.stringify(after),reason}}); }

app.get('/api/health',(_,res)=>res.json({ok:true}));
app.get('/api/ocr/status',(_,res)=>res.json({configured:ocrConfigured(),provider:process.env.OCR_ENDPOINT||null,model:process.env.OCR_MODEL||'gpt-4o-mini'}));
app.post('/api/applications/:id/ocr',async(req,res)=>{try{if(!req.body?.imageDataUrl)return res.status(400).json({error:'缺少 imageDataUrl'});const result=await recognizeImage(req.body.imageDataUrl);res.json(result)}catch(error:any){res.status(502).json({error:error.message})}});
app.get('/api/applications',async(_,res)=>res.json(await prisma.application.findMany({include:{evaluations:{orderBy:{createdAt:'desc'},take:1},scores:true,fields:true,approvals:true},orderBy:{updatedAt:'desc'}})));
app.get('/api/applications/:id',async(req,res)=>{const item=await prisma.application.findUnique({where:{id:req.params.id},include:{attachments:true,fields:true,scores:true,evaluations:{orderBy:{createdAt:'desc'}},approvals:true,reviews:true,ledgerEntries:true}}); if(!item)return res.status(404).json({error:'申请不存在'}); res.json(item);});
app.post('/api/applications',async(req,res)=>{const b=req.body||{}; const id=crypto.randomUUID(); const a=await prisma.application.create({data:{projectId:id,applicationNo:`AI-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`,region:b.region,district:b.district,applicant:b.applicant,hospital:b.hospital,kol:b.kol,projectName:b.projectName,meetingDate:b.meetingDate?new Date(b.meetingDate):undefined,requestedAmount:b.requestedAmount?Number(b.requestedAmount):undefined}}); await audit(a.id,'CREATE',a); res.status(201).json(a);});
app.post('/api/applications/demo',async(_,res)=>{
  let a=await prisma.application.findFirst({where:{projectName:fieldsFromDemo.projectName}});
  if(a)return res.json(a);
  const scoreRows=keys.map(key=>({key,category:key,option:key==='meetingLevel'?'省级会议':key==='academicBenefit'?'展台':key==='expertLevel'?null:key==='productType'?'重点增长产品':key==='hospitalValue'?'区域重点医院':key==='monthlySales'?'10万元以上':key==='salesTrend'?null:key==='growthOpportunity'?'明确新增检测量/科室/医院目标':key==='communication'?'区域宣传':'有目标计划',score:key==='meetingLevel'?6:key==='academicBenefit'?4:key==='expertLevel'?null:key==='productType'?8:key==='hospitalValue'?6:key==='monthlySales'?4:key==='salesTrend'?null:key==='growthOpportunity'?10:key==='communication'?2:3,maxScore:Math.max(...options[key].map(x=>x.score)),confirmed:!['expertLevel','salesTrend'].includes(key),evidence:'申请截图/文本提取'}));
  a=await prisma.application.create({data:{projectId:crypto.randomUUID(),applicationNo:'AI-2026-DEMO01',status:'REVIEWING',region:fieldsFromDemo.region,district:fieldsFromDemo.district,applicant:fieldsFromDemo.applicant,hospital:fieldsFromDemo.hospital,kol:fieldsFromDemo.kol,projectName:fieldsFromDemo.projectName,meetingDate:new Date(fieldsFromDemo.meetingDate),requestedAmount:3,fields:{create:Object.entries(fieldsFromDemo).map(([key,value])=>({key,sourceValue:String(value),confirmedValue:String(value),sourceText:String(value),confidence:key==='kol'||key==='meetingDate'?0.48:0.94,needsConfirmation:key==='kol'||key==='meetingDate'}))},scores:{create:scoreRows}}});
  const e=evaluate(toScoreInput(await prisma.scoreBreakdown.findMany({where:{applicationId:a.id}})),3,Infinity);
  await prisma.evaluation.create({data:{applicationId:a.id,rawScore:e.rawScore,percentile:e.percentile,grade:e.grade,recommendedRange:'1-2万元',defaultAmount:1.5,completeness:e.completeness,minPossible:43,maxPossible:58,confidence:e.confidence,risks:'专家层级、销量趋势待确认；申请金额高于当前建议。',narrative:narrative(a,e)}});
  return res.status(201).json(a);
});
app.post('/api/applications/:id/attachments',upload.single('file'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'缺少文件'}); const item=await prisma.attachment.create({data:{applicationId:req.params.id,fileName:req.file.originalname,filePath:req.file.path,mimeType:req.file.mimetype,extractionStatus:'UPLOADED'}}); res.status(201).json(item);});
app.post('/api/applications/:id/ocr-service',upload.single('file'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'缺少文件'});try{const bytes=await readFile(req.file.path);const form=new FormData();form.append('file',new Blob([bytes],{type:req.file.mimetype}),String(req.file.originalname));form.append('application_id',req.params.id);form.append('rule_version','2026.1');const endpoint=process.env.OCR_SERVICE_URL||'http://127.0.0.1:8100';const headers:Record<string,string>={};if(process.env.OCR_SERVICE_TOKEN)headers.Authorization=`Bearer ${process.env.OCR_SERVICE_TOKEN}`;const response=await fetch(`${endpoint}/v1/recognize`,{method:'POST',headers,body:form});const data:any=await response.json();if(!response.ok)return res.status(response.status).json(data);const applicationId=req.params.id;const appFields:any={};for(const [key,item] of Object.entries(data.fields||{})){const value=String((item as any)?.value||'');if(!value)continue;await prisma.extractedField.upsert({where:{applicationId_key:{applicationId,key}},create:{applicationId,key,sourceValue:value,confirmedValue:value,sourceText:String((item as any)?.sourceText||''),confidence:Number((item as any)?.confidence||0),needsConfirmation:Boolean((item as any)?.needsConfirmation)},update:{sourceValue:value,sourceText:String((item as any)?.sourceText||''),confidence:Number((item as any)?.confidence||0),needsConfirmation:Boolean((item as any)?.needsConfirmation)}});if(['region','district','applicant','hospital','kol','projectName','currentSales','targetSales','background','benefits'].includes(key))appFields[key]=value;if(key==='requestedAmount')appFields.requestedAmount=Number(value)||undefined;if(key==='meetingDate')appFields.meetingDate=new Date(value);}if(Object.keys(appFields).length)await prisma.application.update({where:{id:applicationId},data:{...appFields,status:'REVIEWING'}});res.json(data)}catch(error:any){res.status(502).json({error:`OCR服务调用失败：${error.message}`})}});
app.post('/api/applications/:id/ocr',async(req,res)=>{try{const dataUrl=String(req.body?.imageDataUrl||'');const match=dataUrl.match(/^data:([^;]+);base64,(.+)$/);if(!match)return res.status(400).json({error:'imageDataUrl 格式无效'});const bytes=Buffer.from(match[2],'base64');const form=new FormData();form.append('file',new Blob([bytes],{type:match[1]}),'upload-image');form.append('application_id',req.params.id);form.append('rule_version','2026.1');const endpoint=process.env.OCR_SERVICE_URL||'http://127.0.0.1:8100';const headers:Record<string,string>={};if(process.env.OCR_SERVICE_TOKEN)headers.Authorization=`Bearer ${process.env.OCR_SERVICE_TOKEN}`;const response=await fetch(`${endpoint}/v1/recognize`,{method:'POST',headers,body:form});const data=await response.json();if(!response.ok)return res.status(response.status).json(data);res.json(data)}catch(error:any){res.status(502).json({error:`OCR服务调用失败：${error.message}`})}});
app.post('/api/applications/:id/extract',async(req,res)=>{const a=await prisma.application.findUnique({where:{id:req.params.id}}); if(!a)return res.status(404).json({error:'申请不存在'}); const text=req.body?.text||''; const updates:any={}; for(const [key,value] of Object.entries({...fieldsFromDemo,...req.body?.fields}))if(value)updates[key]=String(value); await Promise.all(Object.entries(updates).map(([key,value])=>prisma.extractedField.upsert({where:{applicationId_key:{applicationId:a.id,key}},create:{applicationId:a.id,key,sourceValue:value as string,confirmedValue:value as string,sourceText:value as string,confidence:.72,needsConfirmation:false},update:{sourceValue:value as string,confirmedValue:value as string,sourceText:text||value as string,confidence:.72,needsConfirmation:false}}))); await prisma.application.update({where:{id:a.id},data:{status:'EXTRACTED'}}); res.json({fields:updates,adapter:'local-demo'});});
app.patch('/api/applications/:id/fields',async(req,res)=>{for(const [key,value] of Object.entries(req.body.fields||{})){const text=String(value);await prisma.extractedField.upsert({where:{applicationId_key:{applicationId:req.params.id,key}},create:{applicationId:req.params.id,key,sourceValue:text,confirmedValue:text,confidence:1,needsConfirmation:false},update:{confirmedValue:text,confidence:1,needsConfirmation:false}});if((keys as string[]).includes(key)){const opt=options[key as ScoreKey].find(x=>x.label===text);await prisma.scoreBreakdown.upsert({where:{applicationId_key:{applicationId:req.params.id,key}},create:{applicationId:req.params.id,key,category:key,option:text||null,score:opt?.score??null,maxScore:Math.max(...options[key as ScoreKey].map(x=>x.score)),confirmed:Boolean(opt),evidence:'人工确认'},update:{option:text||null,score:opt?.score??null,confirmed:Boolean(opt),evidence:'人工确认'}});}} res.json({ok:true});});
app.post('/api/applications/:id/score/recalculate',async(req,res)=>{const scores=await prisma.scoreBreakdown.findMany({where:{applicationId:req.params.id}}); const a=await prisma.application.findUnique({where:{id:req.params.id}}); const e=evaluate(toScoreInput(scores),a?.requestedAmount||undefined,Infinity); const item=await prisma.evaluation.create({data:{applicationId:req.params.id,rawScore:e.rawScore,percentile:e.percentile,grade:e.grade,recommendedRange:e.recommendedRange,defaultAmount:e.defaultAmount,completeness:e.completeness,minPossible:e.minPossible,maxPossible:e.maxPossible,confidence:e.confidence,risks:e.missing.length?`待确认：${e.missing.join('、')}`:'无明显缺失',narrative:narrative(a,e)}}); res.json(item);});
app.post('/api/applications/:id/submit',async(req,res)=>{const a=await prisma.application.update({where:{id:req.params.id},data:{status:'PENDING_APPROVAL'}}); await audit(a.id,'SUBMIT',a); res.json(a);});
app.post('/api/applications/:id/approve',requireRole(UserRole.APPROVER),async(req,res)=>{const {decision,approvedAmount,reason,approver='审批人'}=req.body; if((decision==='CUSTOM'||decision==='AGREE_REQUEST')&&!reason&&approvedAmount===undefined)return res.status(400).json({error:'金额调整需要填写理由'}); const a=await prisma.application.update({where:{id:req.params.id},data:{status:decision==='REJECT'?'REJECTED':'APPROVED'}}); const ap=await prisma.approval.create({data:{applicationId:a.id,decision,approvedAmount:approvedAmount===undefined?undefined:Number(approvedAmount),reason,approver}}); if(decision!=='REJECT')await prisma.ledgerEntry.create({data:{applicationId:a.id,region:a.region,hospital:a.hospital,kol:a.kol,requestedAmount:a.requestedAmount,recommendedAmount:(await prisma.evaluation.findFirst({where:{applicationId:a.id},orderBy:{createdAt:'desc'}}))?.defaultAmount,approvedAmount:Number(approvedAmount||0),year:new Date().getFullYear()}}); await audit(a.id,'APPROVE',ap,reason); res.json(ap);});
app.get('/api/ledger',async(_,res)=>res.json(await prisma.ledgerEntry.findMany({include:{application:true},orderBy:{createdAt:'desc'}})));
app.post('/api/applications/:id/review',async(req,res)=>{const r=await prisma.postEventReview.create({data:{applicationId:req.params.id,targetSales:req.body.targetSales,actualSales:req.body.actualSales,incrementalSales:req.body.incrementalSales,coveredDepartments:req.body.coveredDepartments,actualSpend:req.body.actualSpend,roi:req.body.roi,conclusion:req.body.conclusion}}); res.status(201).json(r);});
app.get('/api/audit-logs',async(_,res)=>res.json(await prisma.auditLog.findMany({orderBy:{createdAt:'desc'},take:100}))); 
const port=Number(process.env.PORT||4000); app.listen(port,()=>console.log(`API listening on http://localhost:${port}`));
process.on('SIGINT',async()=>{await prisma.$disconnect();process.exit(0)});
